# Generated by Django 5.1.1 on 2024-10-26 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customer_alter_product_image_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
